services:
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8080:8000
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    environment:
      - PORT=8000
    env_file:
      - .env.sample
    volumes:
      - ./backend/src:/app
    develop:
      watch:
        - action: rebuild
          path: backend/requirements.txt
        - action: rebuild
          path: backend/Dockerfile
        - action: restart
          path: backend/src
  static_html:
    build: 
      context: ./static_html
      dockerfile: static.Dockerfile
    ports:
      - 8888:8888
    command: python -m http.server 8888
    volumes:
      - ./static_html/src:/app
    